Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/wintest/lib/python3.7/site-packages/jupyter_cache/executors/basic.py", line 163, in execute
    executenb(nb_bundle.nb, cwd=tmpdirname, timeout=timeout)
  File "/usr/share/miniconda3/envs/wintest/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 737, in executenb
    return ep.preprocess(nb, resources, km=km)[0]
  File "/usr/share/miniconda3/envs/wintest/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/usr/share/miniconda3/envs/wintest/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/usr/share/miniconda3/envs/wintest/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
script_dir = os.path.dirname('__file__') #<-- absolute dir the script is in
rel_path_SL = "datasets/data-synthetic-lethals.xlsx"
rel_path_nSL="datasets/data-positive-genetic.xlsx"
rel_path_domains="datasets/proteins-domains-from-Pfam.xlsx"

abs_file_path_SL = os.path.join(script_dir, rel_path_SL)
abs_file_path_nSL = os.path.join(script_dir, rel_path_nSL)
abs_file_path_domains = os.path.join(script_dir, rel_path_domains)


os.chdir('mini_book/docs/') #<-- for binder os.chdir('../')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-2-42ea050eb8a2>[0m in [0;36m<module>[0;34m[0m
[1;32m     10[0m [0;34m[0m[0m
[1;32m     11[0m [0;34m[0m[0m
[0;32m---> 12[0;31m [0mos[0m[0;34m.[0m[0mchdir[0m[0;34m([0m[0;34m'mini_book/docs/'[0m[0;34m)[0m [0;31m#<-- for binder os.chdir('../')[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'mini_book/docs/'
FileNotFoundError: [Errno 2] No such file or directory: 'mini_book/docs/'

